### ISSUE TITLE
Is this repository still being maintainned? 

### ISSUE THREAD

**Issue by tiagocabaco** [ivan-bocharov/stan-vscode#2]
Hi, 

I would like to contribute to the stan highlighting extension in vscode, but first I would like to know if I submit a PR that this will be reviewed by the owner of this repo? 

Thank you very much! 

Cheers

**Comment by ivan-bocharov** [comment]
Hi @tiagocabaco,

Thanks for your interest in contributing to this repo. I welcome all contributions and will definitely review any submitted PR!
