### ISSUE TITLE
add `array` highlighting

### ISSUE THREAD

**Issue by spinkney** [ivan-bocharov/stan-vscode#6]
for example

```stan
data {
  int<lower=0> N;
  array[2] vector[N] x; // old syntax is vector[N] x[2];
  array[2] vector[N] y;
}
```

**Comment by ivan-bocharov** [comment]
Hi @spinkney, thanks for opening the issue. `array` variable type should be highlighted already. Here is the example that you have provided:

![Screenshot from 2021-11-17 12-54-26](https://user-images.githubusercontent.com/706421/142196031-85e3c6ea-24fe-442e-8fc4-f36dfb7a6f24.png)

**Comment by spinkney** [comment]
oh nice!! sorry I missed that!

**Comment by spinkney** [comment]
I just updated vs-code, it's so nice. Thank you for being so responsive! 

![Screen Shot 2021-11-17 at 7 03 53 AM](https://user-images.githubusercontent.com/23704057/142197272-c1630b50-c43c-4ea2-bbcb-180ffb505c7e.png)
