### ISSUE TITLE
complex numbers need to be updated

### ISSUE THREAD

**Issue by spinkney** [ivan-bocharov/stan-vscode#7]
Hi Ivan, 

Brian brought to my attention that complex numbers are incorrectly highlighted. 

vscode shows this: 
<img width="555" alt="Screen Shot 2021-11-28 at 9 03 18 AM" src="https://user-images.githubusercontent.com/23704057/143771141-122a6a45-b776-4b92-ab01-5fed1354a29a.png">

issues: 
* complex is not highlighted
* to_complex is not highlighted
* get_real is not highlighted
* and 3i - 40e-3i + 1e10i should each be highlighted as "green", just like regular numbers

**Comment by ivan-bocharov** [comment]
Hi @spinkney,

Thanks for bringing this to my attention. I'll make a hotfix release in the next couple of days.

**Comment by WardBrian** [comment]
In addition to `complex`, Stan 2.30+ now has `complex_matrix`, `complex_vector`, and `complex_row_vector` types.
